#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: charlton
  pool: 5
  username: glenn
  password: 123456

#test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: charlton
  pool: 5
  username: glenn
  password: 123456

production:
  adapter: postgresql
  encoding: unicode
  database: charlton
  pool: 5
  username: glenn
  password: 123456